### ISSUE TITLE
Can I run without GPU?

### ISSUE THREAD

**Issue by Li-Shu14** [Sense-X/X-Temporal#2]
I failed in  running  `./easy_setup.sh` on my mac. The error is :
```
Traceback (most recent call last):
  File "setup.py", line 28, in <module>
    torch.utils.cpp_extension.CUDA_HOME = _find_cuda_home()
  File "setup.py", line 20, in _find_cuda_home
    nvcc = subprocess.check_output(['which', 'nvcc']).decode().rstrip('\r\n')
  File "/opt/anaconda3/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/opt/anaconda3/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['which', 'nvcc']' returned non-zero exit status 1.
```
It seems that cuda is necessary but MAC doesn't have gpu.

**Comment by Li-Shu14** [comment]
Please ignore my stupid question for there is actually no point in running on a cpu-only machine.
